first = input('What is your first name? ')
last = input('What is your last name? ')
email = input('What is your email address? ')
phone = input('What is your phone number? ')
job = input('What is your job title? ')
id_num = input('What is your ID number? ')
hair = input('What color is your hair? ')
month = input('What month did you begin working at the company? ')
eyes = input('What color are your eyes? ')
train = input('Have you completed the advanced training program? Yes/No ')

print("\nThe ID Card is:")
print("----------------------------------------")
print(f"{last.upper()}, {first.capitalize()}")
print(job.title())
print(f"ID: {id_num}")
print()
print(email.lower())
print(phone)
print()
print(f"Hair: {hair:15} Eyes: {eyes}")
print(f"Month: {month:14} Training: {train}")
print("----------------------------------------")
