adjective = input('Adjective: ')
animal = input('Animal: ')
verb1 = input('Verb: ')
exclamation = input('Exclamation: ')
verb2 = input('Verb: ')
verb3 = input('Verb: ')
verb4 = input('Past-Tense Verb: ')
room = input('Room of the house: ')
verb5 = input('Verb: ')
name = input('Nonsense word: ')
adjective2 = input('Adjective: ')
adverb = input('Adverb: ')

print('The other day, I was really in trouble. It all started when I saw a very')
print(f'{adjective.lower()} {animal.lower()} {verb1.lower()} down the hallway. "{exclamation.capitalize()}!" I yelled. But all')
print(f'I could think to do was to {verb2.lower()} over and over. Miraculously,')
print(f'that caused it to stop, but not before it tried to {verb3}')
print('right in front of my family.')
print(f'Later, when I {verb4.lower()} in the {room}, the {animal.lower()} copied me. ')
print(f'I have never seen {animal.lower()}s do that before so I decided to {verb5.lower()} to see')
print(f'if it would copy me again. Boy, was I surprised to see it do the same thing!')
print(f'I decided to keep it as a pet, so I named it {name.title()}. It seemed')
print(f'very {adjective2.lower()} about its new name and we all lived {adverb.lower()} ever after.')